"use client"
import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import home from "../public/home.png";
import search from "../public/search.png";
import homemobile from "../public/homeMobileview.png";
import login from "../public/login.png";
import register from "../public/register.png";
import bookDetail from "../public/bookDetail.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Thet Htet Soe
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              React Js(Next Js) and Node Js Learner
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              
              Someone who love learning new things continuously. 
            </p>
            {/* <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div> */}
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My Learning Journey</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my learnig journey to become Web Developer
              ,At first, I do self-study about PHP (Laravel FrameWork) that use OOP design pattern, and learned Mysql Database and front end React Js.
              After that, I focus to become javascript based full stack application developer. So, I have joined  
               <span className="text-teal-500"> Turing react 6th batch</span> with recomendation of my friend.
              I was very excited  about learning Js ,typeSctipt, functional programming, error handling etc. 
             I have been learning Frontend  <span className="text-teal-500"> React Js (NEXT Js) </span>, Redux
             , backend <span className="text-teal-500">Express JS </span> , 
             <span className="text-teal-500"> Mongo Database (NoSql)</span> 
              and UI   <span className="text-teal-500">  Tailwand Css </span>
             
             
            
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            BELOW is the projects that I have created
            </p>
          </div>
          <div className="lg:flex gap-3">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Ecommerce project <br></br>
                (Laravel)
              </h3>
             
              <h4 className="py-4 text-teal-600">using</h4>
              <p className="text-teal-600 py-1">Ui -bootstrapt</p>
              <p className="text-teal-600 py-1">Frontend- react js</p>
              <p className="text-teal-600 py-1">Backend - laravel</p>
              <p className="text-teal-600 py-1">Database- Mysql</p>
              <p className="text-teal-600 py-1"> Api call- Axios </p>
             <p className="text-teal-600 py-1">Api security- Laravel Santum</p>
            
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Bookstore Project <br></br>
                (node Js)
              </h3>
              <p className="py-2">
               Here is the repo link of Bookstore full stack project 
               <br /> Frontend: <a href="https://github.com/ThetHtetS/bookStore-Next-Js-" className="underline">click here</a>
               <br /> Backend: <a href="https://github.com/ThetHtetS/bookStore-ExpressJs-" className="underline">click here</a>
              </p>
              <h4 className="py-4 ">created using following Technology</h4>
              
              <p className="text-teal-600 py-1">Tailwand Css (responsive design)</p>
              <p className="text-teal-600 py-1">React Js (NEXT JS)</p>
              <p className="text-teal-600 py-1">Redux</p>
              <p className="text-teal-600 py-1">Express Js</p>
              <p className="text-teal-600 py-1">Mongo DB (NoSql)</p>
              <p className="text-teal-600 py-1">network fetch Axios</p>
              <p className="text-teal-600 py-1">API security - jsonwebtoken</p>
              <p className="text-teal-600 py-1">password hash- bcript library</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">React + firebase project</h3>
              <p className="py-2">
              This is my Generator Spare part and customer Management App
              </p>
              <h4 className="py-4 ">Using</h4>
              <p className="text-teal-600 py-1">Ui - Tailwand Css</p>
              <p className="text-teal-600 py-1">React Js , useContex ,useReducer for light/dark switcher</p>
              <p className="text-teal-600 py-1">create custom hook to fetch data from firebase</p>
              <p className="text-teal-600 py-1">Hosted on firebase on this link <a href="https://pti-app-4cae3.web.app/" className="underline">
              https://pti-app-4cae3.web.app/</a></p>
              <p className="text-teal-600 py-1">  note: not working with full text search </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Bookstore project featured and design</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              This Bookstore project have two main sector, User Side and Admin Side verified by roll-based authuntication
             
              <h1 className="text-teal-500 text-2xl my-3"> featured avalible at normal user side </h1>
                 <p>-Register New User </p>
                 <p>-Login user </p>
                 <p>-View Book List </p>
                 <p>-view Category </p>
                 <p>-view book by Category </p>
                 <p>-add book to shopping cart </p>
                 <p>-increase or decrease product qty </p>
                 <p>-Remove produce from Cart </p>
                 <p>-checkout or make order to admin </p>
                 <p>-view order history and order status </p>
                 <p>-Book detail and add review </p>
                 <p>-search book feature </p>

              <h1 className="text-teal-500 text-2xl my-3"> featured avalible at Admin Side </h1>
                <p>-Category CRUD</p>
                <p>-Book CRUD   </p>
                <p>-User List   </p>
                <p>-view Order   </p>
                <p>-view Order By Status   </p>
                <p>-view view Order with Date Range   </p>
                <p>-Order Detail    </p>
                <p>-Change Order Status   </p>
                <p>-Admin Panel   </p>
               
            </p>
            {/* <h1 className="text-2xl py-2 leading-8 text-teal-600 dark:text-gray-200">
              let see with image
            </h1> */}
          </div>
          {/* <div className=" gap-10 py-10">
            <div className=" ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={home}
              />
            </div>
            <div className=" ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={homemobile}
              />
            </div>
            <div className=" ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={search}
              />
            </div>
            <div className=" ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={login}
              />
            </div>
            <div className=" ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={register}
              />
            </div>
            <div className="">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={bookDetail}
              />
            </div>
          </div> */}
        </section>
      </main>
    </div>
  );
}
